# Overrides command line arguments
override option_one = did_override
# Does not override command line arguments
option_two = not_override
CONFIG ?= .config
export CONFIG
all: 

	echo $CONFIG
	echo $(option_one)
	echo $(option_two)
